services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on: jupyter
    ports:
      - "80:80"
      - "443:443"
    network:
      - docker-hadoop_default
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt/archive/haithanhhoang.info/:/etc/nginx/ssl:ro
    restart: unless-stopped