services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - docker-hadoop_default
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - cert_folder:/etc/letsencrypt:ro
    restart: unless-stopped

networks:
  docker-hadoop_default:
    external: true
    name: docker-hadoop_default

volumes:
  cert_folder:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /etc/letsencrypt