services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./etc/letsencrypt/live/haithanhhoang.info:/etc/nginx/ssl:ro
    restart: unless-stopped